//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LapShopPr.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ResAdmin {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ResAdmin() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("LapShopPr.Resources.ResAdmin", typeof(ResAdmin).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to action.
        /// </summary>
        public static string lblaction {
            get {
                return ResourceManager.GetString("lblaction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CategoryName.
        /// </summary>
        public static string lblCategoryName {
            get {
                return ResourceManager.GetString("lblCategoryName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FaceBook.
        /// </summary>
        public static string lblFaceBook {
            get {
                return ResourceManager.GetString("lblFaceBook", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Github.
        /// </summary>
        public static string lblGithub {
            get {
                return ResourceManager.GetString("lblGithub", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gpu.
        /// </summary>
        public static string lblGpu {
            get {
                return ResourceManager.GetString("lblGpu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HardDisk.
        /// </summary>
        public static string lblHardDisk {
            get {
                return ResourceManager.GetString("lblHardDisk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Image.
        /// </summary>
        public static string lblImage {
            get {
                return ResourceManager.GetString("lblImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Item Name.
        /// </summary>
        public static string lblItemName {
            get {
                return ResourceManager.GetString("lblItemName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Item Type.
        /// </summary>
        public static string lblItemType {
            get {
                return ResourceManager.GetString("lblItemType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Linkedin.
        /// </summary>
        public static string lblLinkedin {
            get {
                return ResourceManager.GetString("lblLinkedin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Operating System.
        /// </summary>
        public static string lblOs {
            get {
                return ResourceManager.GetString("lblOs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Price.
        /// </summary>
        public static string lblPrice {
            get {
                return ResourceManager.GetString("lblPrice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Processor.
        /// </summary>
        public static string lblProcessor {
            get {
                return ResourceManager.GetString("lblProcessor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to product name.
        /// </summary>
        public static string lblproduct_name {
            get {
                return ResourceManager.GetString("lblproduct name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Purchase Price.
        /// </summary>
        public static string lblPurchasePrice {
            get {
                return ResourceManager.GetString("lblPurchasePrice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to quantity.
        /// </summary>
        public static string lblquantity {
            get {
                return ResourceManager.GetString("lblquantity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RamSize.
        /// </summary>
        public static string lblRamSize {
            get {
                return ResourceManager.GetString("lblRamSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sales Price.
        /// </summary>
        public static string lblSalesPrice {
            get {
                return ResourceManager.GetString("lblSalesPrice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ScreenReslution.
        /// </summary>
        public static string lblScreenReslution {
            get {
                return ResourceManager.GetString("lblScreenReslution", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ScreenSize.
        /// </summary>
        public static string lblScreenSize {
            get {
                return ResourceManager.GetString("lblScreenSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show in Home Page.
        /// </summary>
        public static string lblShowHomePage {
            get {
                return ResourceManager.GetString("lblShowHomePage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to total.
        /// </summary>
        public static string lbltotal {
            get {
                return ResourceManager.GetString("lbltotal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Weight.
        /// </summary>
        public static string lblWeight {
            get {
                return ResourceManager.GetString("lblWeight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Youtube.
        /// </summary>
        public static string lblYoutube {
            get {
                return ResourceManager.GetString("lblYoutube", resourceCulture);
            }
        }
    }
}
